version: '3.7'
services:
  env:
    build: "./docker"
    tty: true
    volumes:
      - type: bind
        source: "."
        target: "/work"
    working_dir: "/work"
    user: "${UID}:${GID}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
