
# --- build command ---
#   docker build -t csg_sample/tensorflow:21.03-tf2-py3 -f Dockerfile_forAWS .

# --- for AWS ---
#   https://github.com/aws/deep-learning-containers/blob/master/available_images.md
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.4.1-gpu-py37-cu110-ubuntu18.04

#RUN apt update
#RUN apt upgrade -y
#RUN apt install -y libgl1-mesa-dev
#
#RUN pip install opencv-python

# --- https://github.com/Dref360/spectral_metric#requirements ---
RUN pip install keras scikit-learn joblib pandas tqdm seaborn
RUN pip install git+https://github.com/DmitryUlyanov/Multicore-TSNE.git


