
# --- build command ---
#   docker build --network=host -f Dockerfile -t jupyter_nb/module_list .
#
# --- for machine learning ---
FROM jupyter/scipy-notebook:latest

RUN pip install pip-licenses==3.5.4 pipdeptree==2.2.1

