FROM ubuntu:24.10

# Update the package list and install Python
RUN apt update && apt install -y python3 python3-pip python3-dev

# Set Python3 as the default python
RUN ln -s /usr/bin/python3 /usr/bin/python
