# Generated by Django 4.1.5 on 2023-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.IntegerField(default=0, verbose_name='now')),
                ('max', models.IntegerField(default=100, verbose_name='max')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('done', 'done')], default='processing', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SelectFormItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32, verbose_name='Item Name')),
                ('check_status', models.CharField(default='unchecked', max_length=10, verbose_name='Check Box Status')),
                ('radio_status', models.CharField(default='unchecked', max_length=10, verbose_name='Radio Box Status')),
                ('dropdown_status', models.CharField(default='unchecked', max_length=10, verbose_name='Dropdown Status')),
                ('dropdown_status_with_submit', models.CharField(default='unchecked', max_length=10, verbose_name='Dropdown Status with Submit')),
            ],
        ),
        migrations.CreateModel(
            name='TableItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=32, verbose_name='First')),
                ('last', models.CharField(max_length=32, verbose_name='Last')),
                ('handle', models.CharField(max_length=32, verbose_name='Handle')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('upload_file', models.FileField(upload_to='', verbose_name='Upload File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
